# Generated by Django 5.2.4 on 2025-07-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_temporarymanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("task", models.CharField(max_length=255)),
                ("cron_minute", models.CharField(default="*", max_length=10)),
                ("cron_hour", models.CharField(default="*", max_length=10)),
                ("cron_day_of_week", models.CharField(default="*", max_length=10)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
