# Generated by Django 5.2.4 on 2025-07-15 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customscheduledtask"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("status", models.BooleanField(null=True)),
                ("cause", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ("date",),
            },
        ),
        migrations.DeleteModel(
            name="CustomScheduledTask",
        ),
    ]
